[module/backlight]

type = internal/backlight
use-actual-brightness = true

format = <ramp> <label> <bar>

label = %percentage%%

bar-fill = ⏽
bar-empty = ⏽
bar-indicator =
bar-width = 6

; icons
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 

; colors aaaaah part

bar-empty-foreground = #FFFFFF
bar-indicator-foreground = #FFFFFF


bar-gradient = true
bar-foreground-0 = #A507D9
bar-foreground-1 = #5815ef
bar-foreground-2 = #072DD9
bar-foreground-3 = #12FFB6
bar-foreground-4 = #00FF21

ramp-0-foreground = #00FFFF
ramp-1-foreground = #00FFFF
ramp-2-foreground = #00FFFF
ramp-3-foreground = ${colors.yellow}
ramp-4-foreground = ${colors.yellow}

