[module/battery]

type = internal/battery

; Max and min

full-at = 95
low-at = 20


; If you are new, use: ls -1 /sys/class/power_supply/ to find your battery configuration :v
; It may differ between laptops.

battery = BAT1
adapter	= ACAD


; Charging
format-charging = <animation-charging> <label-charging>
format-charging-background = ${colors.black}
format-charging-padding = 1
label-charging = %percentage%%


; Discharging
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${colors.black}
format-discharging-padding = 1
label-discharging = %percentage%%


; Full battery
format-full = <ramp-capacity> <label-full>
format-full-background = ${colors.black}
format-full-padding = 1
label-full = %percentage%%


; Low battery
format-low = <animation-low> <label-low>
format-low-background = ${colors.red}
format-low-padding = 1
label-low = %percentage%%


;;;; Icons aaaaaah part ;;;;;
; Icons taken from Nerd-fonts

; Used for "Charging"
animation-charging-0 = %{T0} %{T-}
animation-charging-1 = %{T0} %{T-}
animation-charging-2 = %{T0} %{T-}
animation-charging-3 = %{T0} %{T-}
animation-charging-4 = %{T0} %{T-}
animation-charging-framerate = 750


; Used when "Discharging" and "Full"
ramp-capacity-gradient = true
ramp-capacity-0 = %{T0} %{T-}
ramp-capacity-1 = %{T0} %{T-} 
ramp-capacity-2 = %{T0} %{T-}
ramp-capacity-3 = %{T0} %{T-}
ramp-capacity-4 = %{T0} %{T-}


; Used when "Low"
animation-low-0 = !
animation-low-1 = " "
animation-low-framerate = 200

; Actually, It would be interesting to now how much energy this animation consumes. 
; Btw, this is a work of an electronic engineer.
