[module/cpu]

type = internal/cpu
interval = 1

format = <ramp-load> <label>
format-background = ${colors.black}
format-padding = 1
label = %percentage:3%%

; Without setting the padding the icon gets covered by the label and with a padding
; <=1 the icon gets so far from the label.
label-padding = 0

; Icon colors
ramp-load-0-foreground = #A507D9  
ramp-load-1-foreground = #12FFB6  
ramp-load-2-foreground = #FFCE01  
ramp-load-3-foreground = #FF0000

; Icons
ramp-load-0 = %{T0} %{T-}
ramp-load-1 = %{T0} %{T-}
ramp-load-2 = %{T0} %{T-}
ramp-load-3 = %{T0} %{T-}
