[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false


; unmuted
format-volume = <ramp-volume>  <label-volume> <bar-volume>
label-volume = %percentage%%
format-volume-foreground = #8c9eff

; muted
format-muted = <label-muted>  <bar-volume>
label-muted = 
format-muted-foreground = ${colors.red}

bar-volume-fill = ⏽
bar-volume-empty = ⏽
bar-volume-indicator =
bar-volume-width = 6

; icon for ramp volume only

ramp-volume-0 =  
ramp-volume-1 = 
ramp-volume-2 = 

; colors aaaaaaaah part 
bar-volume-empty-foreground = #ffffff
bar-volume-indicator-foreground = #ffffff

bar-volume-gradient = true
bar-volume-foreground-0 = #A507D9
bar-volume-foreground-1 = #5815ef
bar-volume-foreground-2 = #072DD9
bar-volume-foreground-3 = #12FFB6
bar-volume-foreground-4 = #00FF21





