[module/temperature]

type = internal/temperature
interval = 0.5
termal-zone = 0

; interval
base-temperature = 20
warm-temperature = 60


units = true

format = <ramp> <label>
label = %temperature-c%
label-foreground = #FF6176

format-warm = <ramp> <label-warm>
label-warm-foreground = #FF0000

ramp-foreground = #FF6176
	
; Icons
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
