#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

$HOME/.config/polybar/launch.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Apps in specific directories


bspc rule -a discord desktop=^8 private=on
bspc rule -a Spotify desktop=^10 private=on


# Floating apps.
bspc rule -a Blueman-manager state=floating
bspc rule -a zoom state=floating

# Nitrogen :v
nitrogen --restore &

# Picom
picom --config ~/.config/picom.conf &

# Polypocket. Dato gracioso: Iniciar la polybar desde la primera linea hace
# que no cargue correctamente.
$HOME/.config/polybar/launch.sh



