[colors]

# Básicos
black = #16161d
red = #c34043
green = #76946a
yellow = #c0a36e
blue = #7e9cd8
magenta = #957fb8
cyan = #6a9589
white = #c8c093

# Claros

black-bright = #727169
red-bright = #e82424
green-bright = #98bb6c
yellow-bright = #e6c384
blue-bright = #7fb4ca
magenta-bright = #938aa9
cyan-bright = #7aa89f
white-bright = #dcd7ba

# Que sera

alert = #A54242
disabled = #707880


